# Configurazione per la sola landing page (progetto_principale/mkdocs.yml)
# VERSIONE CORRETTA

site_url: https://corsi.angelocardellicchio.it/
site_name: Angelo Cardellicchio | Corsi di Informatica
site_author: Angelo Cardellicchio

theme:
  name: material
  language: it
  logo: material/school 
  custom_dir: overrides
  
  # La sezione 'palette' e 'features' devono essere indentate sotto 'theme'
  palette:
    # Modalità chiara
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Modalità scura
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  
  features:
    - navigation.top

# Questa sezione definisce la struttura di navigazione del sito.
# In questo caso, abbiamo solo una pagina.
nav:
  - Home: index.md