site_name: Informatica
site_url: https://corsi.angelocardellicchio.it/informatica/

nav:
  - Home: index.md
  - 1. Introduzione all'informatica:
    - 1.1 Introduzione all'informatica: material/01_intro/01_intro_inf.md
    - 1.2 Rappresentazione dei dati: material/01_intro/02_data_repr.md
    - 1.3 Codifica digitale ed analogica: material/01_intro/03_dig_an.md
    - 1.4 Sistemi di numerazione:
      - 1.4.1 Sistema decimale: material/01_intro/04_num_sis.md
      - 1.4.2 Sistema binario: material
      - 1.4.3 Sistemi esadecimale ed ottale: material
    - 1.5 Algebra di Boole:
      - 1.5.1 Introduzione: material/01_intro/07_boole/01_intro.md
      - 1.5.2 Operazioni fondamentali: material/01_intro/07_boole/02_ops.md
      - 1.5.3 Proprietà delle operazioni fondamentali: material/01_intro/07_boole/03_ops_properties.md
      - 1.5.4 Leggi dell'algebra booleana: material/01_intro/07_boole/04_laws.md
  - 2. Architettura del Calcolatore:
    - 2.1 Porte logiche: material
    - 2.2 L'archietttura di Von Neumann: material
    - 2.3 La CPU:
      - 2.3.1 L'Unità Aritmetico Logica (ALU): material
      - 2.3.2 La Control Unit e il ciclo Fetch-Decode-Execute: material
      - 2.3.3 I Registri: material
    - 2.4 La Gerarchia di Memoria:
      - 2.4.1 Registri, Cache, RAM: material
      - 2.4.2 Memoria di massa: material
    - 2.5 Linguaggio Macchina e Assembly: material
  - 3. Sistemi Operativi:
    - 3.1 Ruolo e Funzioni del Sistema Operativo: material
    - 3.2 Gestione dei Processi:
      - 3.2.1 Cos'è un processo e un thread: material
      - 3.2.2 Lo scheduling della CPU: material
    - 3.3 Gestione della memoria:
      - 3.3.1 L'astrazione della memoria virtuale: material
      - 3.3.2 Paginazione e segmentazione: material
    - 3.4 File System:
      - 3.4.1 Come i dati vengono organizzati su disco: material
    - 3.5 Gestione dell'I/O: material
  - 4. Principi di programmazione e Algoritmi:
    - 4.1 Paradigmi di programmazione: material
    - 4.2 La programmazione strutturata:
      - 4.2.1 Variabili, Tipi di Dato e Scope:  material
      - 4.2.2 Strutture di Controllo: material
      - 4.2.3 Diagrammi di flusso: material
    - 4.3 Le Funzioni e la Ricorsione: material
    - 4.4 Complessità Computazionale: material
    - 4.5 Strutture dati:
      - 4.5.1 Strutture dati elementari: material
      - 4.5.2 Strutture dati complesse: material
    - 4.6 Algoritmi fondamentali:
      - 4.6.1 Algoritmi di Ricerca:
        - 4.6.1.1 Ricerca Lineare: material
        - 4.6.1.2 Ricerca Binaria: material
      - 4.6.2 Algoritmi di Ordinamento:
        - 4.6.2.1 Selection Sort: material
        - 4.6.2.2 Bubble Sort: material
        - 4.6.2.3 Insertion Sort: material
        - 4.6.2.4 Merge Sort: material
        - 4.6.2.5 Quick Sort: material
      - 4.6.3 Algoritmi su Grafi:
        - 4.6.3.1 Breadth First Search: material
        - 4.6.3.2 Depth First Search: material


theme:
  name: material
  language: it

markdown_extensions:
  - admonition # notes make pret4ty
  - attr_list
  - footnotes
  - meta # page-specific context
  - toc:
      permalink: true # inserts an anchor
  - sane_lists # better ul and ol
  - nl2br # newline hard break
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem: # better italic and bold
      smart_enable: asterisk
  - pymdownx.caret # insert text and superscript
  - pymdownx.details # details and summary; work with admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.highlight: # better code, instead of CodeHilite           <--------
      anchor_linenums: false
  - pymdownx.inlinehilite # like codehilite but inline
  - pymdownx.magiclink # auto links
  - pymdownx.mark # highlight text
  - pymdownx.smartsymbols # special symbols
  - pymdownx.superfences: # nest code blocks under other blocks   <-------
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist: # better tasks lists
      custom_checkbox: true
  - pymdownx.tabbed: # auto tabs
      alternate_style: true # auto tabs
  - pymdownx.tilde # strike through cross out text
  - tables
  - md_in_html

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/anhelus
    - icon: fontawesome/solid/paper-plane
      link: mailto:a.cardellicchio@gmail.com

extra_javascript:
  - js/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css

copyright: Copyright &copy; Angelo Cardellicchio - MIT License
